In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[21, 22]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[5, 27], [7, 21], [26, 27], [1, 1, 6], [7, 2, 26], [23, 27], [10, 2, 6], [2, 26], [2, 25], [22, 20]]


In [4]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 5 27  0]
 [ 7 21  0]
 [26 27  0]
 [ 1  1  6]
 [ 7  2 26]
 [23 27  0]
 [10  2  6]
 [ 2 26  0]
 [ 2 25  0]
 [22 20  0]]


In [5]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [6]:
X = padded_reviews
y = sentiment

In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 5)              150       
_________________________________________________________________
flatten (Flatten)            (None, 15)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 16        
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
model.fit(X, y, epochs=50, verbose=True)

Epoch 1/50
1/1 [==============================] - 1s 557ms/step - loss: 0.6992 - accuracy: 0.3000
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6977 - accuracy: 0.3000
Epoch 3/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6962 - accuracy: 0.3000
Epoch 4/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6947 - accuracy: 0.3000
Epoch 5/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6932 - accuracy: 0.3000
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6917 - accuracy: 0.4000
Epoch 7/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6902 - accuracy: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6888 - accuracy: 0.5000
Epoch 9/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6873 - accuracy: 0.5000
Epoch 10/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6858 - accuracy: 0.6000
Epoch 11/50
1/1 [====================

In [9]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 149ms/step - loss: 0.6226 - accuracy: 1.0000


1.0

In [10]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:
weights

array([[ 0.0480088 , -0.06626958,  0.05901707, -0.06996882, -0.09323596],
       [ 0.03318531, -0.0197015 ,  0.01228443,  0.06813733, -0.00570488],
       [-0.05166217,  0.01276314, -0.06444462, -0.0555829 ,  0.03676108],
       [-0.04996726, -0.02106713,  0.01614115,  0.02361487,  0.00480567],
       [-0.03662791, -0.02750338,  0.04581476, -0.0130193 ,  0.00725359],
       [ 0.07848106, -0.07640882,  0.02963108,  0.08151188, -0.03777217],
       [-0.00690086, -0.08813526,  0.0080571 , -0.08359213, -0.00631192],
       [ 0.09945478, -0.01301798,  0.01659344,  0.00450455, -0.01636465],
       [ 0.02184599, -0.04419625, -0.00249971,  0.00436056, -0.00593096],
       [-0.01687856, -0.01346496,  0.03675262, -0.03073455,  0.03388402],
       [-0.04100639,  0.03989474, -0.09047049, -0.02296045,  0.02036896],
       [ 0.00347619,  0.04162693,  0.03959108, -0.0101294 , -0.03038546],
       [ 0.03731895,  0.04251195, -0.02774309, -0.00124542,  0.01846028],
       [ 0.04916015,  0.01982957,  0.0

In [14]:
from numpy import savetxt

In [15]:
savetxt('data.csv', weights, delimiter=',')